###
GET http://localhost:3000/users
Authorization: Bearer 

###
POST http://localhost:4000/register
Content-Type: application/json

{
    "SSN" : 100,
    "userType" : "company",
    "password": "company"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "SSN" : 100,
    "userType" : "doctor",
    "password": "doctor"
}

###
GET http://localhost:4000/tokens

###
POST http://localhost:4000/refresh
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiJ9.MTAw.Vlp-9MwIr8fylhV9C46cGXz4HZ4f7rhzkOeLimSKRTg"
}

###
POST http://localhost:4000/admin/grant-access
Content-Type: application/json

{
    "SSN" : 100,
    "userType" : "patient",
    "resource" : "pharmacy"
}