###
POST http://localhost:4000/register
Content-Type: application/json

{
    "SSN" : 999,
    "userType" : "patient",
    "password": "patient"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "SSN" : 100,
    "userType" : "admin",
    "password": "admin"
}

###
GET http://localhost:4000/tokens

###
POST http://localhost:4000/refresh
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiJ9.OTk5.Chy2l5GJBIOqaikHIrl5mxDMivVH_rUf27QH9H2KDpk"
}

###
POST http://localhost:4000/admin/grant-access
Content-Type: application/json

{
    "SSN" : 999,
    "userType" : "patient",
    "resource" : "patient"
}