###
//Tesing Doctor routes
GET http://localhost:3000/doctors
Authorization: Bearer 

###
GET http://localhost:3000/doctors/ssn/1
Authorization: Bearer 

###
GET http://localhost:3000/doctors/speciality/Cardiology
Authorization: Bearer 

###
GET http://localhost:3000/doctors/experience/1
Authorization: Bearer 
