###
//Testing patient routes
GET http://localhost:3000/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzMjU5NzMsImV4cCI6MTcwMTMyNjAzM30.Jf5MtADVEU21YKfK5lHdTuOgTE9Z0TdfmNsm36yViCU
###
GET http://localhost:3000/patients/email/michaeldavis@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzMjU5NzMsImV4cCI6MTcwMTMyNjAzM30.Jf5MtADVEU21YKfK5lHdTuOgTE9Z0TdfmNsm36yViCU

###
GET http://localhost:3000/patients/gender/Female
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzMjU5NzMsImV4cCI6MTcwMTMyNjAzM30.Jf5MtADVEU21YKfK5lHdTuOgTE9Z0TdfmNsm36yViCU

###
GET http://localhost:3000/patients/drug/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzMjU5NzMsImV4cCI6MTcwMTMyNjAzM30.Jf5MtADVEU21YKfK5lHdTuOgTE9Z0TdfmNsm36yViCU 

###
GET http://localhost:3000/patients/drug/Acetaminophen
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzMjU5NzMsImV4cCI6MTcwMTMyNjAzM30.Jf5MtADVEU21YKfK5lHdTuOgTE9Z0TdfmNsm36yViCU

###
POST http://localhost:4000/subscribe
Content-Type: application/json

{
    "SSN" : 100,
    "userType" : "patient",
    "resource": "pharmacy"
}