###
//Tesing Pharmacy routes
GET http://localhost:3000/pharmacy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzNjYzODEsImV4cCI6MTcwMTM2Njk4MX0.NvCoTl0jxfPDjb2mfSm6kt32t_03lzMQApJJihjLUTI

###
GET http://localhost:3000/pharmacy/id/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzNjYzODEsImV4cCI6MTcwMTM2Njk4MX0.NvCoTl0jxfPDjb2mfSm6kt32t_03lzMQApJJihjLUTI

###
GET http://localhost:3000/pharmacy/email/abcpharmacy@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzNjYzODEsImV4cCI6MTcwMTM2Njk4MX0.NvCoTl0jxfPDjb2mfSm6kt32t_03lzMQApJJihjLUTI

###
GET http://localhost:3000/pharmacy/address/Manhattan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzNjYzODEsImV4cCI6MTcwMTM2Njk4MX0.NvCoTl0jxfPDjb2mfSm6kt32t_03lzMQApJJihjLUTI
